### ISSUE TITLE
Error: Failed to load parser '@babel/eslint' declared in '.eslintrc » plugin:flowtype/recommended': Cannot find module '@babel/eslint'

### ISSUE THREAD

**Issue by kawpii** [gajus/eslint-plugin-flowtype#517]
```
Oops! Something went wrong! :(

ESLint: 8.4.1

Error: Failed to load parser '@babel/eslint' declared in '.eslintrc » plugin:flowtype/recommended': Cannot find module '@babel/eslint'
Require stack:
- /.../node_modules/eslint-plugin-flowtype/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:98:19)
    at Object.resolve (/.../node_modules/@eslint/eslintrc/dist/eslintrc.cjs:1088:46)
    at ConfigArrayFactory._loadParser (/.../node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3235:39)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/.../node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3030:43)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/.../node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2971:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/.../node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3026:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by kawpii** [comment]
Fixed by
 `yarn add -D @babel/eslint-parser`

`.eslintrc`
```
{
   ...
   "parser": "@babel/eslint-parser",
   ...
}
```

**Comment by mtan11** [comment]
I still have the same issue 
`Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Failed to load parser '@babel/eslint' declared in '.eslintrc.js » plugin:flowtype/recommended': Cannot find module '@babel/eslint'
Require stack:`
